### ISSUE TITLE
Error in jaxb-library

### ISSUE THREAD

**Issue by luigidr** [dog-gateway/dog#1]
Hi,

the `jaxb-library` included in this repository is different from the one present at https://github.com/dog-gateway/jaxb-library.
I suppose that a problem occurred in merging the repositories...

**Comment by dbonino** [comment]
Please check if now is fine, and afterward I'll close the issue

**Comment by luigidr** [comment]
No, unfortunately. :-(

The `jaxb-library` included here is a copy of the `semantic-library`, with another name. In this moment, two copies of the `semantic-library` are included: one with the "right" name and the (wanna-be) `jaxb-library`.

**Comment by dbonino** [comment]
ok I got it

**Comment by dbonino** [comment]
Please check now, it should be solved

**Comment by luigidr** [comment]
Solved, thanks!
